NO_LABEL = -1

category_map_20 = [
    0,  # "shoes",
    1,  # "bags",
    2,  # "hat",
    3,  # "necklace",
    4,  # "earring",
    5,  # "ring",
    6,  # "hair",
    7,  # "glasses",
    8,  # "belt",
    9,  # "bracelet",
    10,  # "jacket",
    11,  # "coat",
    12,  # "top",
    13,  # "croptop",
    14,  # "skirt",
    15,  # "pants",
    16,  # "wholebody",
]

mapped_names_20 = [
    "shoes",
    "bags",
    "hat",
    "necklace",
    "earring",
    "ring",
    "hair",
    "glasses",
    "belt",
    "bracelet",
    "jacket",
    "coat",
    "top",
    "croptop",
    "skirt",
    "pants",
    "wholebody",
]

category_map_25 = [
    0,  # "SHOES",
    1,  # "JEWELRIES",
    2,  # "HATS",
    3,  # "OUTWEARS",
    4,  # "PANTS",
    5,  # "SKIRTS",
    6,  # "SWIMWEARS",
    7,  # "TOPS",
    8,  # "WHOLEBODIES",
    9,  # "BAGS",
    10,  # "BELTS",
    11,  # "GLASSES",
    12,  # "GLOVES",
    13,  # "HAIR_ACCESSORIES",
    14,  # "KEY_RING",
    15,  # "SCARF/MUFFLER",
    16,  # "SOCKS",
    17,  # "TIE",
    18,  # "WATCHES",
]

mapped_names_25 = [
    "SHOES",
    "JEWELRIES",
    "HATS",
    "OUTWEARS",
    "PANTS",
    "SKIRTS",
    "SWIMWEARS",
    "TOPS",
    "WHOLEBODIES",
    "BAGS",
    "BELTS",
    "GLASSES",
    "GLOVES",
    "HAIR_ACCESSORIES",
    "KEY_RING",
    "SCARF/MUFFLER",
    "SOCKS",
    "TIE",
    "WATCHES",
]

category_map_merged_20 = [
    0,  # "shoes",
    8,  # "bags",
    2,  # "hat",
    1,  # "necklace",
    1,  # "earring",
    1,  # "ring",
    11,  # "hair",
    10,  # "glasses",
    9,  # "belt",
    1,  # "bracelet",
    3,  # "jacket",
    3,  # "coat",
    6,  # "top",
    6,  # "croptop",
    5,  # "skirt",
    4,  # "pants",
    7,  # "wholebody",
]

category_map_merged_25 = [
    0,  # "SHOES",
    1,  # "JEWELRIES",
    2,  # "HATS",
    3,  # "OUTWEARS",
    4,  # "PANTS",
    5,  # "SKIRTS",
    NO_LABEL,  # "SWIMWEARS",
    6,  # "TOPS",
    7,  # "WHOLEBODIES",
    8,  # "BAGS",
    9,  # "BELTS",
    10,  # "GLASSES",
    NO_LABEL,  # "GLOVES",
    11,  # "HAIR_ACCESSORIES",
    NO_LABEL,  # "KEY_RING",
    NO_LABEL,  # "SCARF/MUFFLER",
    NO_LABEL,  # "SOCKS",
    NO_LABEL,  # "TIE",
    1,  # "WATCHES",
]

mapped_names_merged = [
    "SHOES",
    "JEWELRIES",
    "HATS",
    "OUTWEARS",
    "PANTS",
    "SKIRTS",
    "TOPS",
    "WHOLEBODIES",
    "BAGS",
    "BELTS",
    "GLASSES",
    "HAIR_ACCESSORIES",
]

category_map = category_map_25
mapped_names = mapped_names_25
